version: '3.4'

services:
  einstallment.api:
    image: ${DOCKER_REGISTRY-}einstallmentapi
    build:
      context: .
      dockerfile: EInstallment.Api/Dockerfile
  einstallment.seq:
    image: datalust/seq:latest
    container_name: einstallment-seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
