# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore EInstallment.sln
    - name: Build
      run: dotnet build EInstallment.sln --no-restore
    - name: Architecture-test
      run: dotnet test ./EInstallment.ArchitectureTest/EInstallment.ArchitectureTest.csproj --no-build --verbosity normal
    - name: Test
      if: always()
      run: dotnet test ./EInstallment.Application.UnitTest/EInstallment.Application.UnitTest.csproj --no-build --verbosity normal
